apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: ebs-sc
