apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  selector:
    app: clickhouse
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
      name: http
  type: LoadBalancer   # Optional: For external access
