apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kc-php-api-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jahswilling/knowledgecity_test.git
    targetRevision: HEAD
    path: "./kubernates_manifest/php_app"
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
